In [6]:
#Importing Required Libs
import numpy as np
import pandas as pd
from sklearn import linear_model

In [25]:
#Reading Dataset 
df = pd.read_csv("add.csv")
df['a']

0     2
1    10
2     8
3     1
4     8
5     5
6     3
7     5
8     1
Name: a, dtype: int64

In [26]:
#Features and labels extracting for training
features = df[['a','b']]
labels= df['sum']

In [27]:
#Creating the Classifier for model training
reg = linear_model.LinearRegression()
reg.fit(features,labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
#PREDICTION TIME ( TESTING )
reg.predict([[23,23]])

array([46.])

In [29]:
reg.predict([[45,10]])

array([55.])

In [30]:
reg.predict([[1000,2000]])

array([3000.])